---
name: zoo-dev
director_uuid: c5f8d0da-f8ac-4918-a1a3-0a846fb97d09

releases:
- name: zoo.hybris
  version: latest

compilation:
  cloud_properties:
    name: random
  network: network2
  reuse_compilation_vms: true
  workers: 6

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 30
  serial: false
  update_watch_time: 1000-30000

resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: network2
  size: 3
  stemcell:
    name: bosh-warden-boshlite-ubuntu-lucid-go_agent
    version: latest

networks:
- name: network2
  subnets:
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
      - 10.244.2.1
    static:
      - 10.244.2.2

  - cloud_properties:
      name: random
    range: 10.244.2.40/30
    reserved:
      - 10.244.2.41
    static:
      - 10.244.2.42
  - cloud_properties:
      name: random
    range: 10.244.2.44/30
    reserved:
      - 10.244.2.45
    static:
      - 10.244.2.46
  - cloud_properties:
      name: random
    range: 10.244.2.48/30
    reserved:
      - 10.244.2.49
    static:
      - 10.244.2.50

  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []

jobs:
- instances: 3
  name: zookeeper_z1
  networks:
  - name: network2
    static_ips:
      - 10.244.2.42
      - 10.244.2.46
      - 10.244.2.50
  resource_pool: small_z1
  template: zookeeper
  properties:
    zookeeper:
      servers:
        - 10.244.2.42
        - 10.244.2.46
        - 10.244.2.50

properties: {}
