---
zookeeper/zookeeper-3.4.6.tar.gz:
  object_id: 42470f2d-ee86-4923-834b-29a7e6a8620b
  sha: !binary |-
    MmE5ZTUzZjU5OTBkZmUwOTY1ODM0YTUyNWZiY2FkMjI2YmY5MzQ3NA==
  size: 17699306
java7/openjdk-1.7.0_55.tar.gz:
  object_id: ac6c8e9e-2aaf-4fb5-92a4-9f60b8f24ada
  sha: !binary |-
    MDc4OGI5MWIzNWJmZGM2MjgxNDMxMDNiMTdkZTMxOTRjMzlhMzA1YQ==
  size: 31534443
