meta:
  environment: zookeeper-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: zookeeper
    networks:
      - name: zookeeper1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: zookeeper1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.30.0/30
    reserved:
    - 10.244.30.1
    static:
    - 10.244.30.2

  - cloud_properties:
      name: random
    range: 10.244.30.4/30
    reserved:
    - 10.244.30.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.30.8/30
    reserved:
    - 10.244.30.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.30.12/30
    reserved:
    - 10.244.30.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.30.16/30
    reserved:
    - 10.244.30.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.30.20/30
    reserved:
    - 10.244.30.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.30.24/30
    reserved:
    - 10.244.30.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.30.28/30
    reserved:
    - 10.244.30.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.30.32/30
    reserved:
    - 10.244.30.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.30.36/30
    reserved:
    - 10.244.30.37
    static: []
